# Generated by Django 3.2.7 on 2021-09-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_articlepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='intro',
            field=models.CharField(blank=True, help_text='News introduction', max_length=140),
        ),
    ]
